<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <LangVersion>default</LangVersion>
        
        <Title>EventSourcing.Abstractions</Title>
        <Authors>Andreas Naumann</Authors>
        <Version>2.0.0-preview-20250620.1</Version>
        <Copyright>2025 @ Andreas Naumann</Copyright>
        <PackageProjectUrl>https://github.com/mrmorrandir/EventSourcing</PackageProjectUrl>
        <PackageLicenseFile>LICENSE.txt</PackageLicenseFile>
        <RepositoryUrl>https://github.com/mrmorrandir/EventSourcing</RepositoryUrl>
        <RepositoryType>git</RepositoryType>
        <PackageTags>EventSourcing, Events, EventStore</PackageTags>
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
        <PackageReleaseNotes></PackageReleaseNotes>
        <RootNamespace>EventSourcing</RootNamespace>
    </PropertyGroup>

    <PropertyGroup>
        <!--This is for symbols in the NuGet package-->
        <AllowedOutputExtensionsInPackageBuildOutputFolder>$(AllowedOutputExtensionsInPackageBuildOutputFolder);.pdb</AllowedOutputExtensionsInPackageBuildOutputFolder>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="FluentResults" Version="3.16.0"/>
        <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.5"/>
    </ItemGroup>

    <ItemGroup>
        <None Include="..\..\LICENSE.txt" Pack="true" PackagePath="LICENSE.txt"/>
    </ItemGroup>

</Project>
