<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <LangVersion>default</LangVersion>
        
        <Title>EventSourcing.Abstractions</Title>
        <Description>Contracts, marker attributes and shared abstractions for EventSourcing.</Description>
        <PackageReadmeFile>README.md</PackageReadmeFile>
        <PackageReleaseNotes>Initial stable 2.0.0 release with core abstractions, runtime integration, source-generator support, projections and publisher extensibility.</PackageReleaseNotes>
        <RootNamespace>EventSourcing</RootNamespace>
    </PropertyGroup>

    <PropertyGroup>
        <!--This is for symbols in the NuGet package-->
        <AllowedOutputExtensionsInPackageBuildOutputFolder>$(AllowedOutputExtensionsInPackageBuildOutputFolder);.pdb</AllowedOutputExtensionsInPackageBuildOutputFolder>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="FluentResults" Version="4.0.0" />
        <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.18" />
    </ItemGroup>

    <ItemGroup>
        <None Include="README.md" Pack="true" PackagePath="\"/>
        <None Include="..\..\LICENSE.txt" Pack="true" PackagePath="LICENSE.txt"/>
    </ItemGroup>

</Project>
