<Project>
    <PropertyGroup>
        <Version>2.0.0</Version>
        <Authors>Andreas Naumann</Authors>
        <Copyright>2025 @ Andreas Naumann</Copyright>
        <PackageProjectUrl>https://github.com/mrmorrandir/EventSourcing</PackageProjectUrl>
        <PackageLicenseFile>LICENSE.txt</PackageLicenseFile>
        <RepositoryUrl>https://github.com/mrmorrandir/EventSourcing</RepositoryUrl>
        <RepositoryType>git</RepositoryType>
        <PackageTags>EventSourcing, Events, EventStore</PackageTags>
        <PublishRepositoryUrl>true</PublishRepositoryUrl>
        <EmbedUntrackedSources>true</EmbedUntrackedSources>
        <IncludeSymbols>true</IncludeSymbols>
        <SymbolPackageFormat>snupkg</SymbolPackageFormat>
        <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
        <ContinuousIntegrationBuild Condition="'$(CI)' == 'true'">true</ContinuousIntegrationBuild>
    </PropertyGroup>
</Project>
