version: "3.2"
services:
  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: 'rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672
    environment:
        RABBITMQ_DEFAULT_USER: 'guest'
        RABBITMQ_DEFAULT_PASS: 'guest'
    networks:
      - rabbitmq_dev_net

networks:
  rabbitmq_dev_net:
    driver: bridge