services:
  rabbitmq:
    image: rabbitmq:4.1-management
    container_name: 'rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    restart: always
    networks:
      - rabbitmq_dev_net

networks:
  rabbitmq_dev_net:
    driver: bridge