<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <IsPackable>false</IsPackable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Mediator.Abstractions" Version="3.0.2" />
      <PackageReference Include="Mediator.SourceGenerator" Version="3.0.2">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\EventSourcing.SourceGenerators.Target.Domain\EventSourcing.SourceGenerators.Target.Domain.csproj" />
    </ItemGroup>

</Project>
