<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <Version>2.0.0-preview-20250917.1</Version>
        <Title>EventSourcing.Publishers.RabbitMQ</Title>
        <Authors>Andreas Naumann</Authors>
        <Description>Extend the event sourcing system with RabbitMQ.
            Events are published with the help of the RabbitMQ.Client library.
        </Description>
        <Copyright>2025 @ Andreas Naumann</Copyright>
        <PackageProjectUrl>https://github.com/mrmorrandir/EventSourcing</PackageProjectUrl>
        <PackageLicenseFile>LICENSE.txt</PackageLicenseFile>
        <RepositoryUrl>https://github.com/mrmorrandir/EventSourcing</RepositoryUrl>
        <RepositoryType>git</RepositoryType>
        <PackageTags>EventSourcing, Events, EventStore</PackageTags>
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
        
    </PropertyGroup>

    <PropertyGroup>
        <!--This is for symbols in the NuGet package-->
        <EmbedUntrackedSources>true</EmbedUntrackedSources>
        <AllowedOutputExtensionsInPackageBuildOutputFolder>$(AllowedOutputExtensionsInPackageBuildOutputFolder);.pdb</AllowedOutputExtensionsInPackageBuildOutputFolder>
    </PropertyGroup>
    
    <ItemGroup>
        <PackageReference Include="Microsoft.SourceLink.GitHub" Version="8.0.0" PrivateAssets="All"/>
        <PackageReference Include="RabbitMQ.Client" Version="7.1.2"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\EventSourcing.Publishers\EventSourcing.Publishers.csproj"/>
        <ProjectReference Include="..\EventSourcing\EventSourcing.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <None Include="..\..\LICENSE.txt" Pack="true" PackagePath="LICENSE.txt"/>
    </ItemGroup>

</Project>
