<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>

        <EnforceExtendedAnalyzerRules>true</EnforceExtendedAnalyzerRules>
        <IsRoslynComponent>true</IsRoslynComponent>
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
        <Version>2.0.0-preview-20250616.1</Version>
        <Title>EventSourcing.SourceGenerators</Title>
        <Authors>Andreas Naumann</Authors>
        <Copyright>2025 @ Andreas Naumann</Copyright>
        <PackageProjectUrl>https://github.com/mrmorrandir/EventSourcing</PackageProjectUrl>
        <PackageLicenseUrl>https://github.com/mrmorrandir/EventSourcing/blob/main/LICENSE.txt</PackageLicenseUrl>
        <RepositoryUrl>https://github.com/mrmorrandir/EventSourcing</RepositoryUrl>
        <RepositoryType>git</RepositoryType>
        <PackageTags>EventSourcing, Events, EventStore</PackageTags>
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>

        <!--SourceLink-->
        <PublishRepositoryUrl>true</PublishRepositoryUrl>
        <EmbedUntrackedSources>true</EmbedUntrackedSources>
        <ContinuousIntegrationBuild>true</ContinuousIntegrationBuild>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.SourceLink.GitHub" Version="8.0.0" PrivateAssets="All" />
        <PackageReference Include="Microsoft.CodeAnalysis.Analyzers" Version="3.3.4">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="4.3.0"/>
        <PackageReference Include="Microsoft.CodeAnalysis.CSharp.Workspaces" Version="4.3.0"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\EventSourcing\EventSourcing.csproj" />
    </ItemGroup>

</Project>
