<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Mediator.Abstractions" Version="2.1.7" />
      <PackageReference Include="Mediator.SourceGenerator" Version="2.1.7">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\tests\EventSourcing.SourceGenerators.Target.Domain\EventSourcing.SourceGenerators.Target.Domain.csproj" />
    </ItemGroup>

</Project>
