using System.Collections.Immutable;
using System.Globalization;
using System.Text;
using System.Text.Json;
using System.Xml.Serialization;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace EventSourcing.SourceGenerators.Serialization;

[Generator]
public class SerializationGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var eventSourcingInfosProvider = context.SyntaxProvider
            .CreateSyntaxProvider(
                (s, _) => InfoProvider.IsRepositoryCandidate(s),
                (ctx, _) => InfoProvider.GetEventSourcingInfo(ctx))
            .Where(esi => esi is not null);

        context.RegisterSourceOutput(eventSourcingInfosProvider.Collect(), (spc, eventSourcingInfos) =>
        {
            if (eventSourcingInfos.IsDefaultOrEmpty)
                return;

            foreach (var eventSourcingInfo in eventSourcingInfos)
            {
                if (eventSourcingInfo!.EventMappers.Count == 0)
                {
                    spc.ReportDiagnostic(Diagnostic.Create(new DiagnosticDescriptor("ESG001", "Aggregate has no 'Create' or 'Apply' methods.", "The aggregate {0} has no 'Create' or 'Apply' methods (with event as parameter) to create mappers for.", "EventSourcing", DiagnosticSeverity.Warning, true), Location.None, eventSourcingInfo.Aggregate.Name));
                    return;
                }

                foreach (var eventMapper in eventSourcingInfo.EventMappers)
                {
                    var eventMapperSource = CreateMapperSource(eventSourcingInfo.Repository, eventMapper);
                    spc.AddSource($"{eventMapper.Mapper.Namespace}.{eventMapper.Mapper.Name}.g.cs", SourceText.From(eventMapperSource, Encoding.UTF8));
                }

                // Create serialization registry
                var serializationRegistrySource = CreateSerializationRegistrySource(eventSourcingInfo);
                spc.AddSource($"{eventSourcingInfo!.Repository.Namespace}.{eventSourcingInfo!.Aggregate.Name}SerializationRegistry.g.cs", SourceText.From(serializationRegistrySource, Encoding.UTF8));

                // Create the dependency injection for the serialization registry
                var serializationRegistrationSource = CreateSerializationDependencyInjectionSource(eventSourcingInfo);
                spc.AddSource($"{eventSourcingInfo!.Repository.Namespace}.{eventSourcingInfo!.Aggregate.Name}SerializationDependencyInjection.g.cs", SourceText.From(serializationRegistrationSource, Encoding.UTF8));
            }

            var completeDependencyInjectionSource = CreateCompleteSerializationDependencyInjectionSource(eventSourcingInfos!);
            spc.AddSource("SerializationDependencyInjection.g.cs", SourceText.From(completeDependencyInjectionSource, Encoding.UTF8));

            foreach (var eventSourcingInfo in eventSourcingInfos)
            {
                var comment = $"//<auto-generated>\n\n{PlainTextCommentSerializer.SerializeToComment(eventSourcingInfo)}";
                spc.AddSource($"Debug_{eventSourcingInfo.Aggregate.Name}.g.cs", SourceText.From(comment, Encoding.UTF8));
            }
            
        });
    }


    private static string CreateMapperSource(InfoProvider.Repository repository, InfoProvider.EventMapper eventMapper)
    {
        var sb = new StringBuilder();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using EventSourcing.Mappers;");

        if (!string.IsNullOrWhiteSpace(eventMapper.Event.Namespace))
            sb.AppendLine($"using {eventMapper.Event.Namespace};");

        sb.AppendLine();

        if (!string.IsNullOrWhiteSpace(repository.Namespace))
            sb.AppendLine($"namespace {repository.Namespace};");

        sb.AppendLine();
        sb.AppendLine($"public partial class {eventMapper.Mapper.Name} : AbstractEventMapper<{eventMapper.Event.Name}>");
        sb.AppendLine("{");
        sb.AppendLine($"    public {eventMapper.Mapper.Name}()");
        sb.AppendLine("    {");
        sb.AppendLine($"        WillSerialize(\"{eventMapper.Event.SchemaName}\");");
        sb.AppendLine($"        CanDeserialize(\"{eventMapper.Event.SchemaName}\");");
        sb.AppendLine("        Configure();");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    partial void Configure();");
        sb.AppendLine("}");

        return sb.ToString();
    }

    private static string CreateSerializationRegistrySource(InfoProvider.EventSourcingInfo eventSourcingInfo)
    {
        var sb = new StringBuilder();
        sb.AppendLine("using EventSourcing;");
        sb.AppendLine("using EventSourcing.Mappers;");
        sb.AppendLine("using FluentResults;");

        var namespaces = new List<string>();
        if (!string.IsNullOrWhiteSpace(eventSourcingInfo.Repository.Namespace))
            namespaces.Add(eventSourcingInfo.Repository.Namespace);
        if (!string.IsNullOrWhiteSpace(eventSourcingInfo.Aggregate.Namespace))
            namespaces.Add(eventSourcingInfo.Aggregate.Namespace);
        //namespaces.AddRange(eventSourcingInfo.EventMappers.Where(em => !string.IsNullOrWhiteSpace(em.Mapper.Namespace)).Select(x => x.Mapper.Namespace));
        namespaces.AddRange(eventSourcingInfo.EventMappers.Where(em => !string.IsNullOrWhiteSpace(em.Event.Namespace)).Select(x => x.Event.Namespace));
        foreach (var ns in namespaces.Distinct())
            sb.AppendLine($"using {ns};");

        sb.AppendLine();
        sb.AppendLine($"namespace {eventSourcingInfo.Repository.Namespace};");
        sb.AppendLine();
        sb.AppendLine($"public class {eventSourcingInfo.Aggregate.Name}SerializationRegistry : ISerializationRegistry<{eventSourcingInfo.Aggregate.Name}>");
        sb.AppendLine("{");
        sb.AppendLine($"    private static readonly StateSerializer<{eventSourcingInfo.Aggregate.Name}> _stateSerializer = new();");

        foreach (var eventMapper in eventSourcingInfo.EventMappers)
            sb.AppendLine($"    private static readonly {eventMapper.Mapper.Name} {eventMapper.Mapper.FieldName} = new();");

        sb.AppendLine("    private static readonly Dictionary<string, Func<string, string, IEvent>> _deserializers = new();");
        sb.AppendLine();
        sb.AppendLine($"    static {eventSourcingInfo.Aggregate.Name}SerializationRegistry()");
        sb.AppendLine("    {");

        foreach (var eventMapper in eventSourcingInfo.EventMappers)
        {
            sb.AppendLine($"        foreach (string schema in {eventMapper.Mapper.FieldName}.Schemas)");
            sb.AppendLine($"            _deserializers.Add(schema, (typeSchema, data) => {eventMapper.Mapper.FieldName}.Deserialize(typeSchema, data));");
        }

        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine($"    public Result<ISerializedState> Serialize({eventSourcingInfo.Aggregate.Name} state)");
        sb.AppendLine("    {");
        sb.AppendLine("        return Result.Try(() => _stateSerializer.Serialize(state));");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    public Result<ISerializedEvent> Serialize(IEvent @event)");
        sb.AppendLine("    {");
        sb.AppendLine("        return @event switch");
        sb.AppendLine("        {");

        // Create serialization cases for each event type
        foreach (var eventMapper in eventSourcingInfo.EventMappers)
            sb.AppendLine($"            {eventMapper.Event.Name} {eventMapper.Event.VariableName} when @event.GetType() == typeof({eventMapper.Event.Name}) => Serialize({eventMapper.Event.VariableName}),");

        sb.AppendLine("            _ => Result.Fail($\"No serializer found for type {@event.GetType().Name}\")");
        sb.AppendLine("        };");
        sb.AppendLine("    }");
        sb.AppendLine();

        foreach (var eventMapper in eventSourcingInfo.EventMappers)
        {
            sb.AppendLine($"    public Result<ISerializedEvent> Serialize({eventMapper.Event.Name} @event)");
            sb.AppendLine("    {");
            sb.AppendLine($"        return Result.Try(() => {eventMapper.Mapper.FieldName}.Serialize(@event));");
            sb.AppendLine("    }");
            sb.AppendLine();
        }

        sb.AppendLine("    public Result<IEvent> Deserialize(string schema, string data)");
        sb.AppendLine("    {");
        sb.AppendLine("        if (!_deserializers.TryGetValue(schema, out var deserializer))");
        sb.AppendLine("            return new Error($\"No deserializer found for type {schema}\");");
        sb.AppendLine();
        sb.AppendLine("        return Result.Try(() => deserializer(schema, data));");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        return sb.ToString();
    }

    private static string CreateSerializationDependencyInjectionSource(InfoProvider.EventSourcingInfo eventSourcingInfo)
    {
        var sb = new StringBuilder();
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine("using EventSourcing.Mappers;");

        var namespaces = new List<string>();
        if (!string.IsNullOrWhiteSpace(eventSourcingInfo.Repository.Namespace))
            namespaces.Add(eventSourcingInfo.Repository.Namespace);
        if (!string.IsNullOrWhiteSpace(eventSourcingInfo.Aggregate.Namespace))
            namespaces.Add(eventSourcingInfo.Aggregate.Namespace);
        //namespaces.AddRange(eventSourcingInfo.EventMappers.Where(x => !string.IsNullOrWhiteSpace(x.Mapper.Namespace)).Select(x => x.Mapper.Namespace));
        namespaces.AddRange(eventSourcingInfo.EventMappers.Where(x => !string.IsNullOrWhiteSpace(x.Event.Namespace)).Select(x => x.Event.Namespace));
        foreach (var ns in namespaces.Distinct())
            sb.AppendLine($"using {ns};");

        sb.AppendLine();
        sb.AppendLine("namespace Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine();
        sb.AppendLine("public static partial class SerializationDependencyInjection");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>");
        sb.AppendLine($"    /// <para>Registers all serialization components for the aggregate {eventSourcingInfo.Aggregate.Name} in the service collection.</para>");
        sb.AppendLine("    /// <para>Use this method in your infrastructure dependency injection to register all serialization components.</para>");
        sb.AppendLine("    /// <para>In order to register everything for the serialization use the <see cref=\"AddSerialization\"/> method.</para>");
        sb.AppendLine("    /// <para>");
        sb.AppendLine("    /// Serialization components that will be registered:");
        sb.AppendLine("    /// <list type=\"bullet\">");
        sb.AppendLine($"    /// <item><see cref=\"ISerializationRegistry&lt;{eventSourcingInfo.Aggregate.Name}&gt;\"/></item>");
        foreach (var eventMapper in eventSourcingInfo.EventMappers)
            sb.AppendLine($"    /// <item><see cref=\"{eventMapper.Mapper.Name}\"/></item>");
        sb.AppendLine("    /// </list>");
        sb.AppendLine("    /// </para>");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine($"    public static IServiceCollection Add{eventSourcingInfo.Aggregate.Name}Serialization(this IServiceCollection services)");
        sb.AppendLine("    {");
        sb.AppendLine($"        services.Add{eventSourcingInfo.Aggregate.Name}Mappers();");
        sb.AppendLine($"        services.Add{eventSourcingInfo.Aggregate.Name}SerializationRegistry();");
        sb.AppendLine("        return services;");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// <para>Registers all mappers for the aggregate in the service collection.</para>");
        sb.AppendLine("    /// <para>Use this method in your infrastructure dependency injection to register all mappers.</para>");
        sb.AppendLine($"    /// <para>In order to register everything for the serialization use the <see cref=\"Add{eventSourcingInfo.Aggregate.Name}Serialization\"/> method.</para>");
        sb.AppendLine("    /// <para>");
        sb.AppendLine("    /// Mappers that will be registered:");
        sb.AppendLine("    /// <list type=\"bullet\">");
        foreach (var eventMapper in eventSourcingInfo.EventMappers)
            sb.AppendLine($"    /// <item><see cref=\"{eventMapper.Mapper.Name}\"/></item>");
        sb.AppendLine("    /// </list>");
        sb.AppendLine("    /// </para>");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine($"    public static IServiceCollection Add{eventSourcingInfo.Aggregate.Name}Mappers(this IServiceCollection services)");
        sb.AppendLine("    {");
        foreach (var eventMapper in eventSourcingInfo.EventMappers)
            sb.AppendLine($"        services.Add{eventMapper.Mapper.Name}();");
        sb.AppendLine("        return services;");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>");
        sb.AppendLine($"    /// <para>Registers the <see cref=\"ISerializationRegistry&lt;{eventSourcingInfo.Aggregate.Name}&gt;\"/> in the service collection.</para>");
        sb.AppendLine($"    /// <para>In order to register everything for the serialization use the <see cref=\"Add{eventSourcingInfo.Aggregate.Name}Serialization\"/> method.</para>");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine($"    public static IServiceCollection Add{eventSourcingInfo.Aggregate.Name}SerializationRegistry(this IServiceCollection services)");
        sb.AppendLine("    {");
        sb.AppendLine($"        services.AddSingleton<ISerializationRegistry<{eventSourcingInfo.Aggregate.Name}>, {eventSourcingInfo.Aggregate.Name}SerializationRegistry>();");
        sb.AppendLine("        return services;");
        sb.AppendLine("    }");
        sb.AppendLine();
        // Add methods for the single mappers
        foreach (var eventMapper in eventSourcingInfo.EventMappers)
        {
            sb.AppendLine("    /// <summary>");
            sb.AppendLine($"    /// <para>Registers the <see cref=\"{eventMapper.Mapper.Name}\"/> in the service collection.</para>");
            sb.AppendLine($"    /// <para>In order to register everything for the serialization use the <see cref=\"Add{eventSourcingInfo.Aggregate.Name}Serialization\"/> method.</para>");
            sb.AppendLine("    /// </summary>");
            sb.AppendLine($"    public static IServiceCollection Add{eventMapper.Mapper.Name}(this IServiceCollection services)");
            sb.AppendLine("    {");
            sb.AppendLine($"        services.AddSingleton<{eventMapper.Mapper.Name}>();");
            sb.AppendLine("        return services;");
            sb.AppendLine("    }");
        }

        sb.AppendLine("}");

        return sb.ToString();
    }

    private static string CreateCompleteSerializationDependencyInjectionSource(ImmutableArray<InfoProvider.EventSourcingInfo> eventSourcingInfos)
    {
        var sb = new StringBuilder();
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine("using EventSourcing.Mappers;");

        var namespaces = new List<string>();
        namespaces.AddRange(eventSourcingInfos.Where(x => !string.IsNullOrWhiteSpace(x.Aggregate.Namespace)).Select(x => x.Aggregate.Namespace));
        foreach (var ns in namespaces.Distinct())
            sb.AppendLine($"using {ns};");

        sb.AppendLine();
        sb.AppendLine("namespace Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine();
        sb.AppendLine("public static partial class SerializationDependencyInjection");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// <para>Registers all serialization components for all aggregates in the service collection.</para>");
        sb.AppendLine("    /// <para>Use this method in your infrastructure dependency injection to register all serialization components.</para>");
        sb.AppendLine("    /// <para>");
        sb.AppendLine("    /// Serialization components that will be registered:");
        sb.AppendLine("    /// <list type=\"bullet\">");
        foreach (var eventSourcingInfo in eventSourcingInfos)
        {
            sb.AppendLine($"    /// <item>ISerializationRegistry&lt;{eventSourcingInfo.Aggregate.Name}&gt; (Implementation: <see cref=\"{eventSourcingInfo.Aggregate.Name}SerializationRegistry\"/>)</item>");
            foreach (var eventMapper in eventSourcingInfo.EventMappers.Where(x => x.Mapper.Namespace == eventSourcingInfo.Repository.Namespace && x.Mapper.Name.StartsWith(eventSourcingInfo.Aggregate.Name)))
                sb.AppendLine($"    /// <item><see cref=\"{eventMapper.Mapper.Name}\"/></item>");
        }

        sb.AppendLine("    /// </list>");
        sb.AppendLine("    /// </para>");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public static IServiceCollection AddSerialization(this IServiceCollection services)");
        sb.AppendLine("    {");
        foreach (var eventSourcingInfo in eventSourcingInfos)
            sb.AppendLine($"        services.Add{eventSourcingInfo.Aggregate.Name}Serialization();");
        sb.AppendLine("        return services;");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }
}