<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\tests\EventSourcing.SourceGenerators.Target.Infrastructure\EventSourcing.SourceGenerators.Target.Infrastructure.csproj" />
    </ItemGroup>

</Project>
