<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <IsPackable>false</IsPackable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\src\EventSourcing\EventSourcing.csproj" />
      <ProjectReference Include="..\EventSourcing.SourceGenerators.Target.Domain\EventSourcing.SourceGenerators.Target.Domain.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="FluentResults" Version="4.0.0" />
    </ItemGroup>

</Project>
