<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
        <Version>1.0.0-beta-2</Version>
        <Title>EventSourcing</Title>
        <Authors>Andreas Naumann</Authors>
        <Description>A small EventSourcing Framework Package.

The persistance is based on the EntityFramworkCore and can be configured via DependencyInjection</Description>
        <Copyright>2025 @ Andreas Naumann</Copyright>
        <PackageProjectUrl>https://github.com/mrmorrandir/EventSourcing</PackageProjectUrl>
        <PackageLicenseUrl>https://github.com/mrmorrandir/EventSourcing/blob/main/LICENSE.txt</PackageLicenseUrl>
        <RepositoryUrl>https://github.com/mrmorrandir/EventSourcing</RepositoryUrl>
        <RepositoryType>git</RepositoryType>
        <PackageTags>EventSourcing, Events, EventStore</PackageTags>
        <PackageVersion>2.0.0-preview-20250612.1</PackageVersion>
        <PackageReleaseNotes></PackageReleaseNotes>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\EventSourcing.Abstractions\EventSourcing.Abstractions.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="FluentResults" Version="3.16.0" />
      <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.5">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
      <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="9.0.5" />
      <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.5" />
      <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="9.0.5" />
      <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="9.0.5" />
      <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="9.0.5" />
      <PackageReference Include="System.Text.Json" Version="9.0.5" />
    </ItemGroup>

    <ItemGroup>
      <Compile Remove="DI\DependencyInjection.cs" />
      <None Include="DI\DependencyInjection.cs" />
      <Compile Remove="DI\EventMapperAssembly.cs" />
      <None Include="DI\EventMapperAssembly.cs" />
      <Compile Remove="DI\EventMapperConfig.cs" />
      <None Include="DI\EventMapperConfig.cs" />
      <Compile Remove="DI\EventMapperType.cs" />
      <None Include="DI\EventMapperType.cs" />
      <Compile Remove="DI\EventMappingOptions.cs" />
      <None Include="DI\EventMappingOptions.cs" />
      <Compile Remove="DI\EventMappingOptionsBuilder.cs" />
      <None Include="DI\EventMappingOptionsBuilder.cs" />
      <Compile Remove="DI\EventProjectionAssembly.cs" />
      <None Include="DI\EventProjectionAssembly.cs" />
      <Compile Remove="DI\EventProjectionConfig.cs" />
      <None Include="DI\EventProjectionConfig.cs" />
      <Compile Remove="DI\EventProjectionOptions.cs" />
      <None Include="DI\EventProjectionOptions.cs" />
      <Compile Remove="DI\EventProjectionOptionsBuilder.cs" />
      <None Include="DI\EventProjectionOptionsBuilder.cs" />
      <Compile Remove="DI\EventSourcingOptionsBuilder.cs" />
      <None Include="DI\EventSourcingOptionsBuilder.cs" />
      <Compile Remove="DI\ProjectionType.cs" />
      <None Include="DI\ProjectionType.cs" />
    </ItemGroup>

</Project>
