<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
        <Title>EventSourcing</Title>
        <Authors>Andreas Naumann</Authors>
        <Version>2.0.0-preview-20250618.1</Version>
        <Description>A small EventSourcing Framework Package.

            The persistance is based on the EntityFramworkCore and can be configured via DependencyInjection
        </Description>
        <Copyright>2025 @ Andreas Naumann</Copyright>
        <PackageProjectUrl>https://github.com/mrmorrandir/EventSourcing</PackageProjectUrl>
        <PackageLicenseFile>LICENSE.txt</PackageLicenseFile>
        <RepositoryUrl>https://github.com/mrmorrandir/EventSourcing</RepositoryUrl>
        <RepositoryType>git</RepositoryType>
        <PackageTags>EventSourcing, Events, EventStore</PackageTags>
        <PackageReleaseNotes></PackageReleaseNotes>
        <PackageReadmeFile>README.md</PackageReadmeFile>

        <!--SourceLink-->
        <PublishRepositoryUrl>true</PublishRepositoryUrl>
        <EmbedUntrackedSources>true</EmbedUntrackedSources>
        <ContinuousIntegrationBuild>true</ContinuousIntegrationBuild>
    </PropertyGroup>

    <ItemGroup>
        <None Include="README.md" Pack="true" PackagePath="\"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\EventSourcing.Abstractions\EventSourcing.Abstractions.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.SourceLink.GitHub" Version="8.0.0" PrivateAssets="All"/>
        <PackageReference Include="FluentResults" Version="3.16.0"/>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.5">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="9.0.5"/>
        <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.5"/>
        <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="9.0.5"/>
        <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="9.0.5"/>
        <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="9.0.5"/>
        <PackageReference Include="System.Text.Json" Version="9.0.5"/>
    </ItemGroup>

    <ItemGroup>
        <Compile Remove="DI\DependencyInjection.cs"/>
        <Compile Remove="DI\EventMapperAssembly.cs"/>
        <Compile Remove="DI\EventMapperConfig.cs"/>
        <Compile Remove="DI\EventMapperType.cs"/>
        <Compile Remove="DI\EventMappingOptions.cs"/>
        <Compile Remove="DI\EventMappingOptionsBuilder.cs"/>
        <Compile Remove="DI\EventProjectionAssembly.cs"/>
        <Compile Remove="DI\EventProjectionConfig.cs"/>
        <Compile Remove="DI\EventProjectionOptions.cs"/>
        <Compile Remove="DI\EventProjectionOptionsBuilder.cs"/>
        <Compile Remove="DI\EventSourcingOptionsBuilder.cs"/>
        <Compile Remove="DI\ProjectionType.cs"/>
    </ItemGroup>

    <ItemGroup>
      <None Include="..\..\LICENSE.txt" Pack="true" PackagePath="LICENSE.txt"/>
    </ItemGroup>

</Project>
