using System.Collections.Immutable;
using System.Text;
using System.Text.RegularExpressions;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace EventSourcing.SourceGenerators.Aggregators;

[Generator]
public class AggregatorGenerator : IIncrementalGenerator
{
    private static readonly Regex _versionSuffixRegex = new Regex(@"-v[0-9]+$");

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var aggregates = context.SyntaxProvider
            .CreateSyntaxProvider(
                (s, _) => IsRepositoryCandidate(s),
                (ctx, _) => GetRepositoriesAggregateInfo(ctx))
            .Where(info => info is not null);

        context.RegisterSourceOutput(aggregates.Collect(), (spc, infos) =>
        {
            if (infos.IsDefaultOrEmpty)
                return;
            
            foreach (var aggregateInfo in infos)
            {
                var eventInfos = CreateEventInfos(aggregateInfo!);
                if (eventInfos.Length == 0)
                    return;
            
                var aggregatorSource = CreateAggregatorSource(aggregateInfo!, [..eventInfos]);
                spc.AddSource($"{aggregateInfo!.RepositoryNamespace}.{aggregateInfo!.AggregateName}Aggregator.g.cs", SourceText.From(aggregatorSource, Encoding.UTF8));
            }
            
            var dependencyInjectionSource = CreateAggregatorsDependencyInjectionSource(spc, infos!);
            spc.AddSource("AggregatorsDependencyInjection.g.cs", SourceText.From(dependencyInjectionSource, Encoding.UTF8));

            var debugSource = CreateDebugSource(infos);
            spc.AddSource("Debug.g.cs", SourceText.From(debugSource, Encoding.UTF8));

        });
    }

    private static string CreateDebugSource(ImmutableArray<AggregateInfo?> infos)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// This file is generated by the AggregatorGenerator source generator.");
        sb.AppendLine("// It contains debug information about the aggregates and their repositories.");
        sb.AppendLine("// You can use this file to verify the generated aggregators and their dependencies.");
        sb.AppendLine();
        foreach (var info in infos)
        {
            if (info is null)
                continue;
            sb.AppendLine($"// Aggregate {info.AggregateName}");
            sb.AppendLine($"//    Name: {info.AggregateName}");
            sb.AppendLine($"//    Namespace: {info.AggregateNamespace}");
            sb.AppendLine($"//    FullName: {info.AggregateFullName}");
            sb.AppendLine($"//    Repository: {info.RepositoryName}");
            sb.AppendLine($"//    Repository Namespace: {info.RepositoryNamespace}");
            sb.AppendLine($"//    Repository FullName: {info.RepositoryFullName}");
            sb.AppendLine($"//    Create Methods:");
            foreach (var applyMethod in info.CreateMethods)
            {
                sb.AppendLine($"//        {applyMethod.MethodName}");
                sb.AppendLine($"//            FullName: {applyMethod.MethodFullName}");
                sb.AppendLine($"//            Event Name: {applyMethod.EventName}");
                sb.AppendLine($"//            Event Namespace: {applyMethod.EventNamespace}");
                sb.AppendLine($"//            Event FullName{applyMethod.EventFullName}");
                sb.AppendLine($"//            Return Type: {applyMethod.ReturnType}");
            }
            sb.AppendLine($"//    Apply Methods:");
            foreach (var applyMethod in info.ApplyMethods)
            {
                sb.AppendLine($"//        {applyMethod.MethodName}");
                sb.AppendLine($"//            FullName: {applyMethod.MethodFullName}");
                sb.AppendLine($"//            Event Name: {applyMethod.EventName}");
                sb.AppendLine($"//            Event Namespace: {applyMethod.EventNamespace}");
                sb.AppendLine($"//            Event FullName{applyMethod.EventFullName}");
                sb.AppendLine($"//            Return Type: {applyMethod.ReturnType}");
            }

            sb.AppendLine();
        }
        var source = sb.ToString();
        return source;
    }

    private static bool IsRepositoryCandidate(SyntaxNode node)
    {
        if (node is not ClassDeclarationSyntax classDecl)
            return false;

        // Must be partial
        if (!classDecl.Modifiers.Any(m => m.IsKind(SyntaxKind.PartialKeyword)))
            return false;

        // Must have a base list (implements or inherits)
        if (classDecl.BaseList == null)
            return false;

        // Must implement IAggregateRepository<T>
        return classDecl.BaseList.Types
            .Any(t => t.Type.ToString().StartsWith("IRepository<"));
    }

    private static AggregateInfo? GetRepositoriesAggregateInfo(GeneratorSyntaxContext context)
    {
        var classSyntax = (ClassDeclarationSyntax)context.Node;
        var model = context.SemanticModel;
        var repositoryType = ModelExtensions.GetDeclaredSymbol(model, classSyntax) as INamedTypeSymbol;
        if (repositoryType is null)
            return null;

        // Find IRepository<T>
        var repoInterface = repositoryType.AllInterfaces
            .FirstOrDefault(i =>
                i.OriginalDefinition.ToDisplayString() == "EventSourcing.Repositories.IRepository<TAggregate>");

        if (repoInterface is null)
            return null;

        var aggregateType = repoInterface.TypeArguments.FirstOrDefault() as INamedTypeSymbol;
        if (aggregateType is null)
            return null;

        // Analyze aggregateType for Apply and Create methods
       var applyMethods = aggregateType.GetMembers()
            .OfType<IMethodSymbol>()
            .Where(m => m is { Name: "Apply", IsStatic: false, Parameters.Length: 1 })
            .Select(m => {
                var eventType = m.Parameters[0].Type;
                return new MutateMethodInfo
                {
                    MethodName = m.Name,
                    MethodFullName = m.ToDisplayString(),
                    EventNamespace = eventType.ContainingNamespace.ToDisplayString().Replace("<global namespace>",""),
                    EventName = eventType.Name,
                    EventFullName = eventType.ToDisplayString(),
                    ReturnType = m.ReturnType.ToDisplayString()
                };
            })
            .ToList();
        
        var createMethods = aggregateType.GetMembers()
            .OfType<IMethodSymbol>()
            .Where(m => m is { Name: "Create", IsStatic: true, Parameters.Length: 1 })
            .Select(m => {
                var eventType = m.Parameters[0].Type;
                return new MutateMethodInfo
                {
                    MethodName = m.Name,
                    MethodFullName = m.ToDisplayString(),
                    EventNamespace = eventType.ContainingNamespace.ToDisplayString().Replace("<global namespace>",""),
                    EventName = eventType.Name,
                    EventFullName = eventType.ToDisplayString(),
                    ReturnType = m.ReturnType.ToDisplayString()
                };
            })
            .ToList();

        if (applyMethods.Count == 0 && createMethods.Count == 0)
            return null;

        return new AggregateInfo
        {
            AggregateNamespace = aggregateType.ContainingNamespace.ToDisplayString().Replace("<global namespace>",""),
            AggregateName = aggregateType.Name,
            AggregateFullName = aggregateType.ToDisplayString(),
            ApplyMethods = applyMethods,
            CreateMethods = createMethods,
            RepositoryNamespace = repositoryType.ContainingNamespace.ToDisplayString().Replace("<global namespace>",""),
            RepositoryName = repositoryType.Name,
            RepositoryFullName = repositoryType.ToDisplayString()
        };
    }
    
    private static EventInfo[] CreateEventInfos(AggregateInfo info)
    {
        var events = new List<EventInfo>(); ;
        foreach (var createMethod in info.CreateMethods)
        {
            events.Add(new EventInfo
            {
                EventName = createMethod.EventName,
                EventFullName = createMethod.EventFullName,
                EventNamespace = createMethod.EventNamespace,
                EventKebabCaseName = ToKebabCase(createMethod.EventName),
                IsCreateEvent = true
            });
        }
        foreach (var applyMethod in info.ApplyMethods)
        {
            events.Add(new EventInfo
            {
                EventName = applyMethod.EventName,
                EventFullName = applyMethod.EventFullName,
                EventNamespace = applyMethod.EventNamespace,
                EventKebabCaseName = ToKebabCase(applyMethod.EventName, false),
                IsCreateEvent = false
            });
        }

        return events.ToArray();
    }

    private static string CreateAggregatorSource(AggregateInfo info, ImmutableArray<EventInfo> eventInfos)
    {
        var sb = new StringBuilder();
        sb.AppendLine("using EventSourcing;");
        sb.AppendLine("using FluentResults;");

        var namespaces = new List<string>();
        if (!string.IsNullOrWhiteSpace(info.AggregateNamespace))
            namespaces.Add(info.AggregateNamespace);
        namespaces.AddRange(eventInfos.Where(x => !string.IsNullOrWhiteSpace(x.EventNamespace)).Select(x => x.EventNamespace));
        foreach (var eventNamespace in namespaces.Distinct())
            sb.AppendLine($"using {eventNamespace};");
        
        sb.AppendLine();
        sb.AppendLine($"namespace {info.RepositoryNamespace};");
        sb.AppendLine();
        sb.AppendLine($"public class {info.AggregateName}Aggregator : IAggregator<{info.AggregateName}>");
        sb.AppendLine("{");
        sb.AppendLine($"    public Result<{info.AggregateName}> CreateFromEvent(IEvent @event)");
        sb.AppendLine("    {");
        sb.AppendLine("        return @event switch");
        sb.AppendLine("        {");
        
        foreach (var eventInfo in eventInfos.Where(x => x.IsCreateEvent))
            sb.AppendLine($"            {eventInfo.EventName} {char.ToLower(eventInfo.EventName[0]) + eventInfo.EventName.Substring(1)} when @event.GetType() == typeof({eventInfo.EventName}) => CreateFromEvent({char.ToLower(eventInfo.EventName[0]) + eventInfo.EventName.Substring(1)}),");
        
        sb.AppendLine("            _ => Result.Fail($\"Unknown event type: {@event.GetType().Name}\")");
        sb.AppendLine("        };");
        sb.AppendLine("    }");
        sb.AppendLine();
        
        foreach (var eventInfo in eventInfos.Where(x => x.IsCreateEvent))
        {
            sb.AppendLine($"    public Result<{info.AggregateName}> CreateFromEvent({eventInfo.EventName} @event)");
            sb.AppendLine("    {");
            sb.AppendLine($"        return Result.Try(() => {info.AggregateName}.Create(@event));");
            sb.AppendLine("    }");
            sb.AppendLine();
        }
        
        sb.AppendLine($"    public Result<{info.AggregateName}> ApplyEvent({info.AggregateName} aggregate, IEvent @event)");
        sb.AppendLine("    {");
        sb.AppendLine("        return @event switch");
        sb.AppendLine("        {");
        
        foreach (var eventInfo in eventInfos.Where(x => !x.IsCreateEvent))
            sb.AppendLine($"            {eventInfo.EventName} {char.ToLower(eventInfo.EventName[0]) + eventInfo.EventName.Substring(1)} when @event.GetType() == typeof({eventInfo.EventName}) => ApplyEvent(aggregate, {char.ToLower(eventInfo.EventName[0]) + eventInfo.EventName.Substring(1)}),");
        
        sb.AppendLine("            _ => Result.Fail($\"Unknown event type: {@event.GetType().Name}\")");
        sb.AppendLine("        };");
        sb.AppendLine("    }");
        
        foreach (var eventInfo in eventInfos.Where(x => !x.IsCreateEvent))
        {
            sb.AppendLine($"    public Result<{info.AggregateName}> ApplyEvent({info.AggregateName} aggregate, {eventInfo.EventName} @event)");
            sb.AppendLine("    {");
            sb.AppendLine($"        return Result.Try(() => aggregate.Apply(@event));");
            sb.AppendLine("    }");
            sb.AppendLine();
        }
        
        sb.AppendLine("}");

        return sb.ToString();
    }
    
    private static string CreateAggregatorsDependencyInjectionSource(SourceProductionContext context, ImmutableArray<AggregateInfo> aggregateInfos)
    {
        var sb = new StringBuilder();
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine("using EventSourcing;");
        
        var namespaces = new List<string>();
        namespaces.AddRange(aggregateInfos.Where(x => !string.IsNullOrWhiteSpace(x.AggregateNamespace)).Select(x => x.AggregateNamespace));
        namespaces.AddRange(aggregateInfos.Where(x => !string.IsNullOrWhiteSpace(x.RepositoryNamespace)).Select(x => x.RepositoryNamespace));
        foreach (var eventNamespace in namespaces.Distinct())
            sb.AppendLine($"using {eventNamespace};");

        sb.AppendLine();
        sb.AppendLine("namespace Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine();
        sb.AppendLine("public static partial class AggregatorsDependencyInjection");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// <para>Registers all aggregators in the service collection.</para>");
        sb.AppendLine("    /// <para>Use this method in your infrastructure dependency injection to register all aggregators.</para>");
        sb.AppendLine("    /// <para>");
        sb.AppendLine("    /// Aggregators that will be registered:");
        
        sb.AppendLine("    /// <list type=\"bullet\">");
        foreach (var info in aggregateInfos)
            sb.AppendLine($"    /// <item>IAggregator&lt;{info.AggregateName}&gt; (Implementation: <see cref=\"{info.AggregateName}Aggregator\"/>)</item>");
        
        sb.AppendLine("    /// </list>");
        sb.AppendLine("    /// </para>");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public static void AddAggregators(this IServiceCollection services)");
        sb.AppendLine("    {");

        foreach (var info in aggregateInfos)
            sb.AppendLine($"        services.Add{info.AggregateName}Aggregator();");

        sb.AppendLine("    }");
        
        foreach (var info in aggregateInfos) 
        {
            sb.AppendLine();    
            sb.AppendLine($"    /// <summary>");
            sb.AppendLine($"    /// <para>Registers the {info.AggregateName} aggregator in the service collection.</para>");
            sb.AppendLine($"    /// <para>In order to register all aggregators use the <see cref=\"AddAggregators\"/> method.</para>");
            sb.AppendLine($"    /// </summary>");
            sb.AppendLine($"    public static IServiceCollection Add{info.AggregateName}Aggregator(this IServiceCollection services)");
            sb.AppendLine("    {");
            sb.AppendLine($"        services.AddSingleton<IAggregator<{info.AggregateName}>, {info.AggregateName}Aggregator>();");
            sb.AppendLine($"        return services;");
            sb.AppendLine("    }");
        }
        
        sb.AppendLine("}");
        sb.AppendLine();
        
        return sb.ToString();
    }

    
    private static string ToKebabCase(string type, bool withVersion = true)
    {
        var kebabCaseName = string.Concat(type.Select((x, i) => i > 0 && char.IsUpper(x) ? "-" + x : x.ToString())).ToLower();
        // Check if the kebab case name already has a version number with a regex
        if (!_versionSuffixRegex.IsMatch(kebabCaseName) && withVersion)
            kebabCaseName += "-v1"; // default versioning
        return kebabCaseName;
    }
    
    private class AggregateInfo
    {
        public string AggregateNamespace = "";
        public string AggregateName = "";
        public string AggregateFullName = "";
        public List<MutateMethodInfo> ApplyMethods = new();
        public List<MutateMethodInfo> CreateMethods = new();
        public string RepositoryNamespace = "";
        public string RepositoryName = "";
        public string RepositoryFullName = "";
    }

    private class MutateMethodInfo
    {
        public string MethodName = "";
        public string MethodFullName = "";
        public string EventNamespace = "";
        public string EventName = "";
        public string EventFullName = "";
        public string ReturnType = "";
    }

    private class EventInfo
    {
        public string EventName = "";
        public string EventFullName = "";
        public string EventNamespace = "";
        public string EventKebabCaseName = "";
        public bool IsCreateEvent = false;
    }
}