using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace EventSourcing.SourceGenerators.Dependencies;

[Generator]
public class EventSourcingDependencyInjectionGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var repositories = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: (s, _) => IsRepositoryCandidate(s),
                transform: (ctx, _) => GetRepositoryInfo(ctx))
            .Where(info => info is not null);

        context.RegisterSourceOutput(repositories.Collect(), (spc, infos) =>
        {
            if (infos.IsDefaultOrEmpty)
                return;
            
            var repositoryDependencyInjectionSource = CreateRepositoryDependencyInjectionSource(infos!);
            spc.AddSource($"EventSourcingDependencyInjection.g.cs", SourceText.From(repositoryDependencyInjectionSource, Encoding.UTF8));

            var optionsSource = CreateEventSourcingOptionsSource();
            spc.AddSource($"EventSourcingOptions.g.cs", SourceText.From(optionsSource, Encoding.UTF8));
        });
    }
    private static bool IsRepositoryCandidate(SyntaxNode node)
    {
        if (node is not ClassDeclarationSyntax classDecl)
            return false;

        // Must be partial
        if (!classDecl.Modifiers.Any(m => m.IsKind(Microsoft.CodeAnalysis.CSharp.SyntaxKind.PartialKeyword)))
            return false;

        // Must have a base list (implements or inherits)
        if (classDecl.BaseList == null)
            return false;

        // Must implement IAggregateRepository<T>
        return classDecl.BaseList.Types
            .Any(t => t.Type.ToString().StartsWith("IRepository<"));
    }
    
    private static RepositoryInfo? GetRepositoryInfo(GeneratorSyntaxContext context)
    {
        var classSyntax = (ClassDeclarationSyntax)context.Node;
        var model = context.SemanticModel;
        var classSymbol = model.GetDeclaredSymbol(classSyntax) as INamedTypeSymbol;
        if (classSymbol == null)
            return null;

        // Find IAggregateRepository<T>
        var repoInterface = classSymbol.AllInterfaces
            .FirstOrDefault(i =>
                i.OriginalDefinition.ToDisplayString() == "EventSourcing.Repositories.IRepository<TAggregate>");

        if (repoInterface == null)
            return null;

        var aggregateType = repoInterface.TypeArguments.FirstOrDefault() as INamedTypeSymbol;
        if (aggregateType == null)
            return null;

        return new RepositoryInfo
        {
            AggregateNamespace = aggregateType.ContainingNamespace.ToDisplayString().Replace("<global namespace>",""),
            AggregateName = aggregateType.Name,
            AggregateFullName = aggregateType.ToDisplayString(),
            RepositoryNamespace = classSymbol.ContainingNamespace.ToDisplayString().Replace("<global namespace>",""),
            RepositoryName = classSymbol.Name,
            RepositoryFullName = classSymbol.ToDisplayString(),
        };
    }
    private static string CreateRepositoryDependencyInjectionSource(ImmutableArray<RepositoryInfo> infos)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("using System;");
        sb.AppendLine("using EventSourcing;");
        sb.AppendLine("using EventSourcing.Stores;");
        sb.AppendLine("using EventSourcing.Contexts;");
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine("using Microsoft.Extensions.Logging;");
        sb.AppendLine("using Microsoft.Extensions.Options;");
        sb.AppendLine("using Microsoft.EntityFrameworkCore;");
        sb.AppendLine("using Microsoft.EntityFrameworkCore.Diagnostics;");
        sb.AppendLine();
        sb.AppendLine("namespace Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine();
        sb.AppendLine("#nullable enable");
        sb.AppendLine("public static partial class EventSourcingDependencyInjection");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// <para>Register everything for the EventSourcing Infrastructure</para>");
        sb.AppendLine("    /// <para>Use this method in your infrastructure dependency injection to register everything at once</para>");
        sb.AppendLine("    /// <para>");
        sb.AppendLine("    /// Calls:");
        sb.AppendLine("    /// <list type=\"bullet\">");
        sb.AppendLine("    /// <item><see cref=\"RepositoryDependencyInjection.AddRepositories\"/></item>");
        sb.AppendLine("    /// <item><see cref=\"SerializationDependencyInjection.AddSerialization\"/></item>");
        sb.AppendLine("    /// <item><see cref=\"AggregatorsDependencyInjection.AddAggregators\"/></item>");
        sb.AppendLine("    /// <item><see cref=\"ProjectorsDependencyInjection.AddProjectors\"/></item>");
        sb.AppendLine("    /// </list>");
        sb.AppendLine("    /// </para>");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    /// <param name=\"services\">The service collection to configure.</param>");
        sb.AppendLine("    /// <returns>The configured service collection.</returns>");
        sb.AppendLine("    /// <remarks>");
        sb.AppendLine("    /// The <c>EventSourcing</c> configuration section is bound to <see cref=\"EventSourcingOptions\"/>.");
        sb.AppendLine("    /// When no connection string is provided, an in-memory database is used.");
        sb.AppendLine("    /// </remarks>");
        sb.AppendLine("    public static IServiceCollection AddEventSourcing(this IServiceCollection services)");
        sb.AppendLine("    {");
        sb.AppendLine("        services.AddOptions<EventSourcingOptions>()");
        sb.AppendLine("            .BindConfiguration(\"EventSourcing\")");
        sb.AppendLine("            .ValidateDataAnnotations()");
        sb.AppendLine("            .ValidateOnStart();");
        sb.AppendLine();
        sb.AppendLine("        return services.AddEventSourcingDatabaseCore();");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// <para>Register everything for the EventSourcing Infrastructure with custom options.</para>");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    /// <param name=\"services\">The service collection to configure.</param>");
        sb.AppendLine("    /// <param name=\"configureOptions\">Configures the Event Sourcing options.</param>");
        sb.AppendLine("    /// <returns>The configured service collection.</returns>");
        sb.AppendLine("    /// <remarks>When no connection string is configured, an in-memory database is used.</remarks>");
        sb.AppendLine("    public static IServiceCollection AddEventSourcing(this IServiceCollection services, Action<EventSourcingOptions> configureOptions)");
        sb.AppendLine("    {");
        sb.AppendLine("        services.AddOptions<EventSourcingOptions>()");
        sb.AppendLine("            .Configure(configureOptions)");
        sb.AppendLine("            .ValidateDataAnnotations()");
        sb.AppendLine("            .ValidateOnStart();");
        sb.AppendLine();
        sb.AppendLine("        return services.AddEventSourcingDatabaseCore();");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// <para>Register everything for the EventSourcing Infrastructure with custom database context options.</para>");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    /// <param name=\"services\">The service collection to configure.</param>");
        sb.AppendLine("    /// <param name=\"optionsAction\">Configures the Event Sourcing database context using registered services.</param>");
        sb.AppendLine("    /// <returns>The configured service collection.</returns>");
        sb.AppendLine("    public static IServiceCollection AddEventSourcing(this IServiceCollection services, Action<IServiceProvider, DbContextOptionsBuilder> optionsAction)");
        sb.AppendLine("    {");
        sb.AppendLine("        return services.AddEventSourcingDatabaseCore(optionsAction);");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    private static IServiceCollection AddEventSourcingDatabaseCore(this IServiceCollection services, Action<IServiceProvider, DbContextOptionsBuilder>? optionsAction = null)");
        sb.AppendLine("    {");
        sb.AppendLine("        if (optionsAction is not null)");
        sb.AppendLine("        {");
        sb.AppendLine("            services.AddDbContext<IEventStoreDbContext, EventStoreDbContext>(optionsAction);");
        sb.AppendLine("        }");
        sb.AppendLine("        else");
        sb.AppendLine("        {");
        sb.AppendLine("            services.AddDbContext<IEventStoreDbContext, EventStoreDbContext>((serviceProvider, optionsBuilder) =>");
        sb.AppendLine("            {");
        sb.AppendLine("                var options = serviceProvider.GetRequiredService<IOptions<EventSourcingOptions>>().Value;");
        sb.AppendLine("                if (string.IsNullOrEmpty(options.ConnectionString))");
        sb.AppendLine("                {");
        sb.AppendLine("                    optionsBuilder.UseInMemoryDatabase(\"EventSourcing-Database\")");
        sb.AppendLine("                        .ConfigureWarnings(x => x.Ignore(InMemoryEventId.TransactionIgnoredWarning));");
        sb.AppendLine("                    return;");
        sb.AppendLine("                }");
        sb.AppendLine();
        sb.AppendLine("                optionsBuilder.UseSqlServer(options.ConnectionString);");
        sb.AppendLine("            });");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        services.AddScoped<IEventStore, EventStore>();");
        sb.AppendLine("        services.AddScoped<IStateStore, StateStore>();");
        sb.AppendLine("        services.AddRepositories();");
        sb.AppendLine("        services.AddSerialization();");
        sb.AppendLine("        services.AddAggregators();");
        sb.AppendLine("        services.AddProjectors();");
        sb.AppendLine();
        sb.AppendLine("        return services;");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// <para>Initialize and apply any required configurations for the EventSourcing Infrastructure.</para>");
        sb.AppendLine("    /// <para>This method should be called to ensure the event sourcing database is properly set up, including applying migrations if necessary.</para>");
        sb.AppendLine("    /// <para>");
        sb.AppendLine("    /// Operations performed:");
        sb.AppendLine("    /// <list type=\"bullet\">");
        sb.AppendLine("    /// <item>Creates a scoped service provider.</item>");
        sb.AppendLine("    /// <item>Logs information and warnings about the database state.</item>");
        sb.AppendLine("    /// <item>Applies database migrations unless the database is in-memory.</item>");
        sb.AppendLine("    /// </list>");
        sb.AppendLine("    /// </para>");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    /// <param name=\"serviceProvider\">The service provider used to resolve dependencies required for the EventSourcing setup.</param>");
        sb.AppendLine("    public static void UseEventSourcing(this IServiceProvider serviceProvider)");
        sb.AppendLine("    {");
        sb.AppendLine("        using var scope = serviceProvider.CreateScope();");
        sb.AppendLine("        var logger = scope.ServiceProvider.GetRequiredService<ILogger<EventStoreDbContext>>();");
        sb.AppendLine("        var dbContext = scope.ServiceProvider.GetRequiredService<IEventStoreDbContext>();");
        sb.AppendLine("        if (dbContext is not EventStoreDbContext concreteDbContext)");
        sb.AppendLine("        {");
        sb.AppendLine("            logger.LogError(\"IEventStoreDbContext is not of type EventStoreDbContext; cannot apply migrations\");");
        sb.AppendLine("            return;");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        if (concreteDbContext.Database.IsInMemory())");
        sb.AppendLine("        {");
        sb.AppendLine("            logger.LogWarning(\"EventSourcing is using InMemory database; skipping migration\");");
        sb.AppendLine("            return;");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        try");
        sb.AppendLine("        {");
        sb.AppendLine("            logger.LogInformation(\"Applying EventSourcing database migrations...\");");
        sb.AppendLine("            concreteDbContext.Database.Migrate();");
        sb.AppendLine("            logger.LogInformation(\"EventSourcing database migrations applied successfully\");");
        sb.AppendLine("        }");
        sb.AppendLine("        catch (Exception ex)");
        sb.AppendLine("        {");
        sb.AppendLine("            logger.LogError(ex, \"An error occurred while migrating the EventSourcing database\");");
        sb.AppendLine("            throw;");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        sb.AppendLine("#nullable restore");
        
        return sb.ToString();
    }

    private static string CreateEventSourcingOptionsSource()
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("namespace EventSourcing;");
        sb.AppendLine();
        sb.AppendLine("public sealed class EventSourcingOptions");
        sb.AppendLine("{");
        sb.AppendLine("    public string? ConnectionString { get; set; }");
        sb.AppendLine("}");
        sb.AppendLine("#nullable restore");

        return sb.ToString();
    }

    private class RepositoryInfo 
    {
        public string AggregateNamespace = "";
        public string AggregateName = "";
        public string AggregateFullName = "";
        public string RepositoryNamespace = "";
        public string RepositoryName = "";
        public string RepositoryFullName = "";
    }
}
